name: 'Install Google Chrome'
description: 'Install Google Chrome'

on:
  pull_request:
    branches:
      - maintenance-3.0.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.0.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      PACKAGES_AUTH_USER:
        description: 'PACKAGES_AUTH_USER'
        required: true
      PACKAGES_AUTH_TOKEN:
        description: 'PACKAGES_AUTH_TOKEN'
        required: true

env:
  REFERENCE_BRANCH: maintenance-3.0.x
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-3.0.x' }}

jobs:
  action:
    runs:
      using: 'composite'
      steps:
        - name: Install google chrome
          shell: bash
          run: |
              wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.133-1_amd64.deb
              sudo apt install -y --allow-downgrades ./google-chrome-stable_114.0.5735.133-1_amd64.deb
              sudo ln -s /usr/bin/google-chrome /usr/bin/chrome
              chrome --version
