name: Cancel

on:
  pull_request:
    branches:
      - maintenance-3.1.x
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  cancel_checks:
    if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Get commit SHA
        id: get_commit_sha
        run: echo "::set-output name=commit_sha::$(jq -r '.after' $GITHUB_EVENT_PATH)"
      - name: List check runs
        id: list_check_runs
        run: |
          checks=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ steps.get_commit_sha.outputs.commit_sha }}/check-runs" | jq -r '.check_runs[] | select(.status == "in_progress") | .id')
          echo "::set-output name=checks::$checks"
      - name: Cancel check runs
        if: steps.list_check_runs.outputs.checks != ''
        run: |
          for check_id in ${{ steps.list_check_runs.outputs.checks }}; do
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" "https://api.github.com/repos/${{ github.repository }}/check-runs/${check_id}/cancel"
          done
