name: Lint

on:
  pull_request:
    branches:
      - maintenance-3.0.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.0.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-3.0.x' }}
  ARTIFACT_ID: view-designer-catalog
  GROUP_ID: org.nuxeo.web.ui.studio
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      
      - run: git config --global user.name "nuxeo-webui-jx-bot" && git config --global user.email "webui@hyland.com"

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          node-version: 14
          scope: '@nuxeo'

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install

      - name: Lint
        run: npm run lint

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
            <mirrors>
              <mirror>
                <id>nos-team</id>
                <mirrorOf>external:*</mirrorOf>
                <url>https://nexus-jx.nos.build.nuxeo.com/repository/maven-group/</url>
              </mirror>
            </mirrors>
            <servers>
              <server>
                <id>nos-team</id>
                <username>nuxeo-webui-jx-bot</username>
                <password>${{ secrets.WEBUI_JX_BOT_GITHUB_ACTIONS_TOKEN }}</password>
              </server>
              <server>
                <id>maven-internal</id>
                <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
              </server>
              <server>
                <id>maven-public-releases</id>
                <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
              </server>
              <server>
                <id>maven-public-snapshots</id>
                <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

      - name: Setup parameters (release)
        if: github.event_name == 'release'
        working-directory: packages/nuxeo-designer-catalog
        run: |
          echo "BRANCH_NAME=maintenance-3.0.x" >> $GITHUB_ENV
          echo "TARGET_PLATFORM=11.3" >> $GITHUB_ENV

      - name: Setup parameters (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "BRANCH_NAME=maintenance-3.0.x" >> $GITHUB_ENV
          echo "TARGET_PLATFORM=11.3" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: packages/nuxeo-designer-catalog
        run: | 
          npm install
          npm install -g gulp

      - name: Generate catalog
        working-directory: packages/nuxeo-designer-catalog
        run: |
          gulp catalog --tp 11.3 --webui-branch maintenance-3.0.x
          gulp hints --tp 11.3

      - name: Bundle the catalog
        run: |
          pushd packages/nuxeo-designer-catalog/data/applications/nuxeo/11.3
          echo "Bundle"
          pwd
          CATALOG_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout -f nuxeo-web-ui/pom.xml)
          echo "Bundle1"
          echo "CATALOG_VERSION=11.3" >> $GITHUB_ENV
          echo "Bundle2"
          CATALOG_NAME=$ARTIFACT_ID-11.3.zip
          echo "Bundle3"
          echo "CATALOG_NAME=$CATALOG_NAME" >> $GITHUB_ENV
          echo "Bundle4"
          zip -q -r $CATALOG_NAME nuxeo-web-ui data hints catalog.json
          popd

